parameters:
    coreshop.dto.add_to_wishlist.class: '%coreshop.storage_list.add_to_list_class%'
    coreshop.form.type.wishlist.validation_groups: [coreshop]
    coreshop.form.type.wishlist_item.validation_groups: [coreshop]
    coreshop.form.type.add_to_wishlist.validation_groups: [coreshop]
    coreshop.form.type.add_to_selectable_wishlist.validation_groups: [coreshop]
    coreshop.form.type.add_to_new_wishlist.validation_groups: [coreshop]
    coreshop.form.type.edit_wishlist.validation_groups: [coreshop]

imports:
    - { resource: services/commands.yml }

services:
    _defaults:
        public: true

    coreshop.factory.wishlist_item.storage_list:
        class: CoreShop\Component\StorageList\Factory\StorageListItemFactory
        decorates: coreshop.factory.wishlist_item
        decoration_priority: 256
        public: false
        arguments:
            - '@coreshop.factory.wishlist_item.storage_list.inner'

    coreshop.factory.wishlist.storage_list:
        class: CoreShop\Component\StorageList\Factory\StorageListFactory
        decorates: coreshop.factory.wishlist
        decoration_priority: 256
        public: false
        arguments:
            - '@coreshop.factory.wishlist.storage_list.inner'

    CoreShop\Bundle\WishlistBundle\Form\Type\WishlistType:
        arguments:
            - '%coreshop.model.wishlist.class%'
            - '%coreshop.form.type.wishlist.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\WishlistBundle\Form\Type\WishlistItemType:
        arguments:
            - '%coreshop.model.wishlist_item.class%'
            - '%coreshop.form.type.wishlist_item.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Bundle\WishlistBundle\Form\Type\AddToWishlistType:
        arguments:
            - '%coreshop.dto.add_to_wishlist.class%'
            - '%coreshop.form.type.add_to_wishlist.validation_groups%'
        tags:
            - { name: form.type }

    CoreShop\Component\Wishlist\Wishlist\WishlistModifier:
        arguments:
            - '@event_dispatcher'
            - '@CoreShop\Component\StorageList\StorageListItemResolverInterface'

    CoreShop\Component\Wishlist\Wishlist\WishlistResolver:
        arguments:
            - '@coreshop.repository.wishlist'
            - '@coreshop.context.storage_list.wishlist'
    
    CoreShop\Bundle\WishlistBundle\Form\Type\WishlistChoiceType:
        arguments:
            - '@CoreShop\Component\Wishlist\Wishlist\WishlistResolver'
        tags:
            - { name: form.type }
