core_shop_storage_list:
    list:
        wishlist:
            context:
                tag: coreshop.context.wishlist
            services:
                manager: CoreShop\Component\StorageList\Manager\StorageListPimcoreModelManager
                modifier: CoreShop\Component\Wishlist\Wishlist\WishlistModifier
                list_resolver: CoreShop\Component\Wishlist\Wishlist\WishlistResolver
                enable_default_store_based_decorator: true
            session:
                enabled: true
                enable_logout_subscriber: true
                key: 'coreshop.wishlist'
            form:
                type: CoreShop\Bundle\WishlistBundle\Form\Type\WishlistType
                add_type: CoreShop\Bundle\WishlistBundle\Form\Type\AddToWishlistType
            resource:
                interface: '%coreshop.interface.wishlist%'
                product_repository: coreshop.repository.stack.wishlist_product
                repository: coreshop.repository.wishlist
                item_repository: coreshop.repository.wishlist_item
                factory: coreshop.factory.wishlist
                item_factory: coreshop.factory.wishlist_item
            routes:
                summary: coreshop_wishlist_summary
                index: coreshop_index
            templates:
                add_to_cart: '@CoreShopFrontend/Product/_addToWishlist.html.twig'
                summary: '@CoreShopFrontend/Wishlist/summary.html.twig'
            controller:
                enabled: true
            expiration:
                enabled: true
                params:
                    days: 20
                    anonymous: true
                    customer: true